// programa: cola01.cpp
// un simple ejemplo del uso de la plantilla queue

#include <cstdlib>
#include <iostream>
#include <queue>

using namespace std;

int main(int argc, char *argv[])
{
	int op;
	queue<int> s;
	
	//for (int i=1; i <= 100; i++)
	//s.push(h);
while (op==0)
	{
		int h
		switch(op){
		case 1:
		s.push(h);
		break;
		case 2:
		cout << s.front() << " " ;
		s.pop();	
		}
	}
	
	cout << endl;
	system("PAUSE");
	return EXIT_SUCCESS;
}
